#define	RTs                     2.0
#define	RT11	                5.0
#define	RT12                    7.0
#define	RT21                    11.0
#define	RT22                    50.0
#define	RT31                    8.0
#define	RT32                    44.0
#define	RTd11                   2.0
#define	RTd12                   2.0
#define	RTd21                   36.0
#define	RTd22                   0.0
#define	RTd31                   38.0
#define	RTd32                   8.0
#define RK11                    0.07
#define RK12                    -0.01
#define RK21                    -0.82
#define RK22					-1.0
#define RK31                    -0.78
#define RK32					-0.9
#define	DRT1					8.0
#define DRTd1					2.0
#define	DRK1					-0.01
#define	DRT2					12.0
#define DRTd2					2.0
#define	DRK2					0.32
#define	DRT3					10.0
#define DRTd3					0.0
#define	DRK3					0.02

/*#define	RT11                5
#define	RT12                    7
#define	RT21                    11
#define	RT22                    50
#define	RT31                    8
#define	RT32                    44
#define	RTd11                   2
#define	RTd12                   2
#define	RTd21                   36
#define	RTd22                   0
#define	RTd31                   38
#define	RTd32                   8
#define RK11                    0.07
#define RK12                    -0.01
#define RK21                    -0.82
#define RK22					-1.0
#define RK31                    -0.78
#define RK32					-0.9 */

//Get Step Response parameter
#define TUNESR1_SR		    0
#define TUNESR1_T 		    1
#define TUNESR1_Ts 		    2
#define TUNESR1_K			3
#define TUNESR1_N			4
#define TUNESR1_Td 		    5
#define TUNESR1_PRIV	    6

//Get Step Response parameter type  <1>
#define TUNESR1_SR_PDT  		PDT_COBJ
#define TUNESR1_T_PDT  		PDT_REAL
#define TUNESR1_Ts_PDT   		PDT_REAL
#define TUNESR1_K_PDT   		PDT_REAL
#define TUNESR1_N_PDT  		PDT_WORD
#define TUNESR1_Td_PDT   		PDT_REAL
#define TUNESR1_PRIV_PDT 		PDT_COBJ

//Get Step Response parameter
#define TUNESR2_SR		    0
#define TUNESR2_T 		    1
#define TUNESR2_Ts 		    2
#define TUNESR2_K	   		3
#define TUNESR2_N	 		4
#define TUNESR2_Td 		    5
#define TUNESR2_PRIV		6

//Get Step Response parameter type  <1>
#define TUNESR2_SR_PDT  	PDT_COBJ
#define TUNESR2_T_PDT  		PDT_REAL
#define TUNESR2_Ts_PDT   	PDT_REAL
#define TUNESR2_K_PDT   	PDT_REAL
#define TUNESR2_N_PDT  		PDT_WORD
#define TUNESR2_Td_PDT   	PDT_REAL
#define TUNESR2_PRIV_PDT 	PDT_COBJ

//Get Step Response parameter
#define TUNESR3_SR		    0
#define TUNESR3_T 		    1
#define TUNESR3_Ts 		    2
#define TUNESR3_K	   			3
#define TUNESR3_N	 			4
#define TUNESR3_Td 		    5
#define TUNESR3_PRIV		    6

//Get Step Response parameter type  <1>
#define TUNESR3_SR_PDT  		PDT_COBJ
#define TUNESR3_T_PDT  		PDT_REAL
#define TUNESR3_Ts_PDT   		PDT_REAL
#define TUNESR3_K_PDT   		PDT_REAL
#define TUNESR3_N_PDT  		PDT_WORD
#define TUNESR3_Td_PDT   		PDT_REAL
#define TUNESR3_PRIV_PDT 		PDT_COBJ

//Get Step Response parameter
#define TUNESR4_SR		    0
#define TUNESR4_T 		    1
#define TUNESR4_Ts 		    2
#define TUNESR4_K	   			3
#define TUNESR4_N	 			4
#define TUNESR4_Td 		    5
#define TUNESR4_PRIV		    6

//Get Step Response parameter type  <1>
#define TUNESR4_SR_PDT  		PDT_COBJ
#define TUNESR4_T_PDT  		PDT_REAL
#define TUNESR4_Ts_PDT   		PDT_REAL
#define TUNESR4_K_PDT   		PDT_REAL
#define TUNESR4_N_PDT  		PDT_WORD
#define TUNESR4_Td_PDT   		PDT_REAL
#define TUNESR4_PRIV_PDT 		PDT_COBJ

//Get Step Response parameter
#define TUNESR5_SR		    0
#define TUNESR5_T 		    1
#define TUNESR5_Ts 		    2
#define TUNESR5_K	   			3
#define TUNESR5_N	 			4
#define TUNESR5_Td 		    5
#define TUNESR5_PRIV		    6

//Get Step Response parameter type  <1>
#define TUNESR5_SR_PDT  		PDT_COBJ
#define TUNESR5_T_PDT  		PDT_REAL
#define TUNESR5_Ts_PDT   		PDT_REAL
#define TUNESR5_K_PDT   		PDT_REAL
#define TUNESR5_N_PDT  		PDT_WORD
#define TUNESR5_Td_PDT   		PDT_REAL
#define TUNESR5_PRIV_PDT 		PDT_COBJ

//Get Step Response parameter
#define TUNESR6_SR		    0
#define TUNESR6_T 		    1
#define TUNESR6_Ts 		    2
#define TUNESR6_K	   			3
#define TUNESR6_N	 			4
#define TUNESR6_Td 		    5
#define TUNESR6_PRIV		    6

//Get Step Response parameter type  <1>
#define TUNESR6_SR_PDT  		PDT_COBJ
#define TUNESR6_T_PDT  		PDT_REAL
#define TUNESR6_Ts_PDT   		PDT_REAL
#define TUNESR6_K_PDT   		PDT_REAL
#define TUNESR6_N_PDT  		PDT_WORD
#define TUNESR6_Td_PDT   		PDT_REAL
#define TUNESR6_PRIV_PDT 		PDT_COBJ


//Simple Disturb Model parameter order <2>
#define DIST_Y			    	0
#define DIST_Y0 			    1
#define DIST_Yh 			    2
#define DIST_U	    			3
#define DIST_T	   				4
#define DIST_Ts					5
#define DIST_K					6
#define DIST_Td					7
#define DIST_Cdelay				8

//Simple MODEL parameter type  <2>
#define DIST_Y_PDT  			PDT_REAL
#define DIST_U_PDT  			PDT_REAL
#define DIST_Y0_PDT   			PDT_REAL
#define DIST_Yh_PDT   			PDT_REAL
#define DIST_T_PDT  			PDT_REAL
#define DIST_Ts_PDT  			PDT_REAL
#define DIST_K_PDT  			PDT_REAL
#define DIST_Td_PDT  			PDT_REAL
#define DIST_Cdelay_PDT  		PDT_COBJ

//Simple MODEL parameter order <2>
#define TUNE1_Y				    0
#define TUNE1_Y0 			    1
#define TUNE1_Yh 			    2
#define TUNE1_U	   		 		3
#define TUNE1_T	   				4
#define TUNE1_Ts				5
#define TUNE1_K					6
#define TUNE1_Td				7
#define TUNE1_Cdelay			8

//Simple MODEL parameter type  <2>
#define TUNE1_Y_PDT  			PDT_REAL
#define TUNE1_U_PDT  			PDT_REAL
#define TUNE1_Y0_PDT   			PDT_REAL
#define TUNE1_Yh_PDT   			PDT_REAL
#define TUNE1_T_PDT  			PDT_REAL
#define TUNE1_Ts_PDT  			PDT_REAL
#define TUNE1_K_PDT  			PDT_REAL
#define TUNE1_Td_PDT  			PDT_REAL
#define TUNE1_Cdelay_PDT  		PDT_COBJ

//Simple MODEL parameter order <2>
#define TUNE2_Y				    0
#define TUNE2_Y0 			    1
#define TUNE2_Yh 			    2
#define TUNE2_U	   		 		3
#define TUNE2_T	   				4
#define TUNE2_Ts				5
#define TUNE2_K					6
#define TUNE2_Td				7
#define TUNE2_Cdelay			8

//Simple MODEL parameter type  <2>
#define TUNE2_Y_PDT  			PDT_REAL
#define TUNE2_U_PDT  			PDT_REAL
#define TUNE2_Y0_PDT   			PDT_REAL
#define TUNE2_Yh_PDT   			PDT_REAL
#define TUNE2_T_PDT  			PDT_REAL
#define TUNE2_Ts_PDT  			PDT_REAL
#define TUNE2_K_PDT  			PDT_REAL
#define TUNE2_Td_PDT  			PDT_REAL
#define TUNE2_Cdelay_PDT  		PDT_COBJ

//Simple MODEL parameter order <2>
#define TUNE3_Y				    0
#define TUNE3_Y0 			    1
#define TUNE3_Yh 			    2
#define TUNE3_U	   		 		3
#define TUNE3_T	   				4
#define TUNE3_Ts				5
#define TUNE3_K					6
#define TUNE3_Td				7
#define TUNE3_Cdelay			8

//Simple MODEL parameter type  <2>
#define TUNE3_Y_PDT  			PDT_REAL
#define TUNE3_U_PDT  			PDT_REAL
#define TUNE3_Y0_PDT   			PDT_REAL
#define TUNE3_Yh_PDT   			PDT_REAL
#define TUNE3_T_PDT  			PDT_REAL
#define TUNE3_Ts_PDT  			PDT_REAL
#define TUNE3_K_PDT  			PDT_REAL
#define TUNE3_Td_PDT  			PDT_REAL
#define TUNE3_Cdelay_PDT  		PDT_COBJ

//Simple MODEL parameter order <2>
#define TUNE4_Y				    0
#define TUNE4_Y0 			    1
#define TUNE4_Yh 			    2
#define TUNE4_U	   		 		3
#define TUNE4_T	   				4
#define TUNE4_Ts				5
#define TUNE4_K					6
#define TUNE4_Td				7
#define TUNE4_Cdelay			8

//Simple MODEL parameter type  <2>
#define TUNE4_Y_PDT  			PDT_REAL
#define TUNE4_U_PDT  			PDT_REAL
#define TUNE4_Y0_PDT   			PDT_REAL
#define TUNE4_Yh_PDT   			PDT_REAL
#define TUNE4_T_PDT  			PDT_REAL
#define TUNE4_Ts_PDT  			PDT_REAL
#define TUNE4_K_PDT  			PDT_REAL
#define TUNE4_Td_PDT  			PDT_REAL
#define TUNE4_Cdelay_PDT  		PDT_COBJ

//Simple MODEL parameter order <2>
#define TUNE5_Y				    0
#define TUNE5_Y0 			    1
#define TUNE5_Yh 			    2
#define TUNE5_U	   		 		3
#define TUNE5_T	   				4
#define TUNE5_Ts				5
#define TUNE5_K					6
#define TUNE5_Td				7
#define TUNE5_Cdelay			8

//Simple MODEL parameter type  <2>
#define TUNE5_Y_PDT  			PDT_REAL
#define TUNE5_U_PDT  			PDT_REAL
#define TUNE5_Y0_PDT   			PDT_REAL
#define TUNE5_Yh_PDT   			PDT_REAL
#define TUNE5_T_PDT  			PDT_REAL
#define TUNE5_Ts_PDT  			PDT_REAL
#define TUNE5_K_PDT  			PDT_REAL
#define TUNE5_Td_PDT  			PDT_REAL
#define TUNE5_Cdelay_PDT  		PDT_COBJ

//Simple MODEL parameter order <2>
#define TUNE6_Y				    0
#define TUNE6_Y0 			    1
#define TUNE6_Yh 			    2
#define TUNE6_U	   		 		3
#define TUNE6_T	   				4
#define TUNE6_Ts				5
#define TUNE6_K					6
#define TUNE6_Td				7
#define TUNE6_Cdelay			8

//Simple MODEL parameter type  <2>
#define TUNE6_Y_PDT  			PDT_REAL
#define TUNE6_U_PDT  			PDT_REAL
#define TUNE6_Y0_PDT   			PDT_REAL
#define TUNE6_Yh_PDT   			PDT_REAL
#define TUNE6_T_PDT  			PDT_REAL
#define TUNE6_Ts_PDT  			PDT_REAL
#define TUNE6_K_PDT  			PDT_REAL
#define TUNE6_Td_PDT  			PDT_REAL
#define TUNE6_Cdelay_PDT  		PDT_COBJ

DWORD 		 _DLLFUNC Tune1ModelParam(PIC wCmd_, WRD wMTU_, WORD pi_, LONG lParam_);
ACRET 		 _DLLFUNC Tune1ModelCalcu(WRD wMeter_);

DWORD 		 _DLLFUNC Tune2ModelParam(PIC wCmd_, WRD wMTU_, WORD pi_, LONG lParam_);
ACRET 		 _DLLFUNC Tune2ModelCalcu(WRD wMeter_);

DWORD 		 _DLLFUNC Tune3ModelParam(PIC wCmd_, WRD wMTU_, WORD pi_, LONG lParam_);
ACRET 		 _DLLFUNC Tune3ModelCalcu(WRD wMeter_);

DWORD   	 _DLLFUNC Tune4ModelParam(PIC wCmd_, WRD wMTU_, WORD pi_, LONG lParam_);
ACRET 		 _DLLFUNC Tune4ModelCalcu(WRD wMeter_);

DWORD 		 _DLLFUNC Tune5ModelParam(PIC wCmd_, WRD wMTU_, WORD pi_, LONG lParam_);
ACRET 		 _DLLFUNC Tune5ModelCalcu(WRD wMeter_);

DWORD   	 _DLLFUNC Tune6ModelParam(PIC wCmd_, WRD wMTU_, WORD pi_, LONG lParam_);
ACRET 		 _DLLFUNC Tune6ModelCalcu(WRD wMeter_);

DWORD   	 _DLLFUNC Dist1ModelParam(PIC wCmd_, WRD wMTU_, WORD pi_, LONG lParam_);
ACRET 		 _DLLFUNC Dist1ModelCalcu(WRD wMeter_);

DWORD   	 _DLLFUNC Dist2ModelParam(PIC wCmd_, WRD wMTU_, WORD pi_, LONG lParam_);
ACRET 		 _DLLFUNC Dist2ModelCalcu(WRD wMeter_);

DWORD   	 _DLLFUNC Dist3ModelParam(PIC wCmd_, WRD wMTU_, WORD pi_, LONG lParam_);
ACRET 		 _DLLFUNC Dist3ModelCalcu(WRD wMeter_);

DWORD 		 _DLLFUNC TuneSR1Param(PIC wCmd_, WRD wMTU_, WORD pi_, LONG lParam_);
ACRET 		 _DLLFUNC TuneSR1Calcu(WRD wMeter_);

DWORD 		 _DLLFUNC TuneSR2Param(PIC wCmd_, WRD wMTU_, WORD pi_, LONG lParam_);
ACRET 		 _DLLFUNC TuneSR2Calcu(WRD wMeter_);

DWORD 		 _DLLFUNC TuneSR3Param(PIC wCmd_, WRD wMTU_, WORD pi_, LONG lParam_);
ACRET 		 _DLLFUNC TuneSR3Calcu(WRD wMeter_);

DWORD   	 _DLLFUNC TuneSR4Param(PIC wCmd_, WRD wMTU_, WORD pi_, LONG lParam_);
ACRET 		 _DLLFUNC TuneSR4Calcu(WRD wMeter_);

DWORD 		 _DLLFUNC TuneSR5Param(PIC wCmd_, WRD wMTU_, WORD pi_, LONG lParam_);
ACRET 		 _DLLFUNC TuneSR5Calcu(WRD wMeter_);

DWORD   	 _DLLFUNC TuneSR6Param(PIC wCmd_, WRD wMTU_, WORD pi_, LONG lParam_);
ACRET 		 _DLLFUNC TuneSR6Calcu(WRD wMeter_);


