//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by tfdlg.rc
//
#define IDD_DLGMATRIX                   101
#define IDC_CURSOR1                     102
#define IDC_DATALINK                    1000
#define IDC_VALUE                       1001
#define IDC_MATRIX_ROW                  1002
#define IDC_MATRIX_COL                  1003
#define IDC_MATRIX_DEFAULT              1004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
