//===================================================================
//
//Zheng zhikai	95-10-4
//===================================================================

#ifndef _COREALL_H__
#define _COREALL_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "core.h"
#include "cgdi.h"
#include "creal.h"
#include "ctint.h"
#include "cbool.h"
#include "cmodu.h"
#include "cface.h"
#include "calgo.h"
#include "cstamp.h"
#include "calarm.h"
#include "cobj.h"
#include "corerw.h"
#include "cfile.h"
#include "crun.h"
#include "cerror.h"
#include "cfwnd.h"
#include "cdbi.h"
#include "csysstmp.h"
#include "csysalgo.h"
#include "csysobj.h"
#include "cstmpfn.h"

#ifdef  __cplusplus
}
#endif

#endif //_COREALL_H__
